[package]
name = "bevy_gizmos"
description = "Visual gizmos to assist with development"
license = "MIT"
repository = "https://github.com/LiamGallagher737/bevy_gizmos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", default-features = false, features = [ "render" ]}
slotmap = "1.0.6"
lazy_static = "1.4.0"
