[package]
name = "bevy_mod_gizmos"
description = "Visual gizmos to aid with development and debugging in Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LiamGallagher737/bevy_gizmos"
readme = "README.md"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", default-features = false, features = [ "render" ]}
bevy_mod_picking = "0.8"
lazy_static = "1.4.0"
